export const listWorks = [
  {
    id: 1,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 2,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 3,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 4,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 5,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 6,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 7,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
  {
    id: 8,
    title: 'Maestro panadero',
    minimunPay: 1000,
    maximunPay: 1500,
    address: 'Lima,Lima, Santa Anita',
    createDate: 'hace 15 horas',
    typeWork: 'Medio tiempo/Tiempo completo',
  },
];
