import {ProposalsReceivedProps} from '../ProposalsReceived/types';
import {ConfigureEmployeProps} from '../ConfigureEmploye/types';
import {EditProfileProps} from '../EditProfile/types';
import {MyPublishedWorksProps} from '../MyPublishedWorks/types';
import {ProfileProps} from '../Profile/types';
import {PublishedSuccesProps} from '../PublishedSuccess/types';
import {RegisterProps} from '../Register/types';
import {EmployeRequestedProps} from '../RequestedEmployes/EmployeRequested/types';
import {RequestedEmployesProps} from '../RequestedEmployes/types';
import {SelectLocationProps} from '../SelectLocation/types';
import {SelectRecordTypeProps} from '../SelectRecordType/types';
import {TermsAndConditionsProps} from '../TermsAndConditions/types';
import {TypeEmployerProps} from '../TypeEmployer/types';
import {WorkDetailProps} from '../WorkDetail/types';
import {RegisteredWorksProps} from './Drawer/Screens/ RegisteredWorks/types';
import {AcceptedWorksProps} from './Drawer/Screens/AcceptedJobs/types';
import {LocationListProps} from '../LocationList/types';
import {CreateCategoriesProps} from './Drawer/Screens/CreateCategories/types';
import {AdminUserAndWorksProps} from './Drawer/Screens/AdminUsersAndWorks/types';
import {ConfirmPayEmployeProps} from '../ConfirmPayEmploye/types';
import {SuscribeMembershipUserProps} from '../SuscribeMembershipUser/type';
import {JobsCategoryProps} from '../JobsCatagory/type';
import {SearchProps} from '../Search/types';
import {FavoritesProps} from '../Favorites/types';
import {SelectPreferencesProps} from '../SelectPreferences/types';

export type MyAppProps = {
  Home: undefined;
  Profile: ProfileProps;
  Search: SearchProps;
  Promotions: undefined;
  Card: undefined;
  Category: undefined;
  Login: undefined;
  SelectRecordType: SelectRecordTypeProps;
  ConfigureEmploye: ConfigureEmployeProps;
  TermsAndConditions: TermsAndConditionsProps;
  PublishedSucces: PublishedSuccesProps;
  EditProfile: EditProfileProps;
  TypeEmployer: TypeEmployerProps;
  Register: RegisterProps;
  SelectLocation: SelectLocationProps;
  WorkDetail: WorkDetailProps;
  RegisteredWorks: RegisteredWorksProps;
  AcceptedWorks: AcceptedWorksProps;
  AdminUserAndWorks: AdminUserAndWorksProps;
  MyPublishedWorks: MyPublishedWorksProps;
  RequestedEmployes: RequestedEmployesProps;
  EmployeRequested: EmployeRequestedProps;
  ProposalsReceived: ProposalsReceivedProps;
  LocationList: LocationListProps;
  CreateCategories: CreateCategoriesProps;
  ConfirmPayEmploye: ConfirmPayEmployeProps;
  SuscribeMembershipUser: SuscribeMembershipUserProps;
  JobsCategory: JobsCategoryProps;
  Favorities: FavoritesProps;
  SelectPreferences: SelectPreferencesProps;
  Onboarding: undefined;
};
