export const ADD_FILTER_CATEGORY = 'ADD_FILTER_CATEGORY';
export const REMOVE_FILTER_CATEGORY = 'REMOVE_FILTER_CATEGORY';
export const ADD_FILTER_TYPEEMPLOYE = 'ADD_FILTER_TYPEEMPLOYE';
export const REMOVE_FILTER_TYPEEMPLOYE = 'REMOVE_FILTER_TYPEEMPLOYE';
export const ADD_RANGE = 'ADD_RANGE';
export const REMOVE_RANGE = 'REMOVE_RANGE';
export const RESET_ALL_FILTERS = 'RESET_ALL_FILTERS';
